version: '2'

services:
  frontend:
    build:
      context: ./frontend/
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 443
    volumes:
      - ./frontend/:/usr/app
    ports:
      - "3000:3000"
    networks:
      - webIII-network

networks:
  webIII-network:
    driver: bridge